name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit Platform Console Standalone
      run: |
        mkdir -p lib
        curl -L -o lib/junit-platform-console-standalone-1.9.2.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar

    - name: Compile
      run: |
        javac -cp lib/junit-platform-console-standalone-1.9.2.jar -d out src/main/java/*.java test/java/*.java

    - name: Test
      run: |
        java -jar lib/junit-platform-console-standalone-1.9.2.jar -cp out --scan-class-path
